#!/usr/bin/env python3
# Lionheart Remake - C/SDL2 port. GPL-3.0.
#
# Build-time codegen. Scans the stripped Java + XML sources and emits C
# dispatch tables for the C/SDL2 port. Replaces Java reflection with
# closed-world enums + factory function pointer arrays.
#
# Outputs (under c-port/gen/):
#   dispatch_states.h     — lh_state_id enum + name table
#   dispatch_features.h   — feature class string registry
#   dispatch_entities.h   — entity class registry (typically 2-3 entries)
#   dispatch_sequences.h  — sequence class registry
#
# Run: python3 c-port/scripts/gen_dispatch.py
import argparse
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
JAVA_ROOT = ROOT / "lionheart-stripped" / "java"
XML_ROOT  = ROOT / "lionheart-stripped" / "assets" / "src" / "main" / "resources"
GEN_DIR   = ROOT / "c-port" / "gen"


def find_state_classes():
    """Enumerate State*.java files under lionheart-game/object/state."""
    states = set()
    state_root = JAVA_ROOT / "lionheart-game" / "src" / "main" / "java" / \
                 "com" / "b3dgs" / "lionheart" / "object" / "state"
    if not state_root.exists():
        return sorted(states)
    for p in state_root.rglob("State*.java"):
        name = p.stem
        if name == "State":
            continue
        states.add(name)
    return sorted(states)


def find_xml_class_values(tag_name):
    """Scan all XML files under XML_ROOT for `<lionengine:TAG>VAL</lionengine:TAG>`
    and return the unique sorted set of VAL strings."""
    if not XML_ROOT.exists():
        return []
    pat = re.compile(rf"<lionengine:{tag_name}>([^<]+)</lionengine:{tag_name}>")
    seen = set()
    for p in XML_ROOT.rglob("*.xml"):
        try:
            txt = p.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            continue
        for m in pat.finditer(txt):
            seen.add(m.group(1).strip())
    return sorted(seen)


def find_sequence_classes():
    """Subclasses of Sequence (Loading, Menu, Scene, ScenePicture, Continue,
    intro/Part*, extro/Part*, extro/Credits, etc.)."""
    seqs = set()
    base = JAVA_ROOT / "lionheart-game" / "src" / "main" / "java" / \
           "com" / "b3dgs" / "lionheart"
    if not base.exists():
        return sorted(seqs)
    seq_re = re.compile(r"\bextends\s+Sequence\b")
    for p in base.rglob("*.java"):
        try:
            txt = p.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            continue
        if seq_re.search(txt):
            seqs.add(p.stem)
    return sorted(seqs)


def slug(s):
    """Convert StateLanaSlide -> STATE_LIANA_SLIDE."""
    out = []
    for i, c in enumerate(s):
        if c.isupper() and i > 0 and not s[i-1].isupper():
            out.append("_")
        out.append(c.upper())
    return "".join(out)


HEADER_BANNER = """/*
 * Lionheart Remake - C/SDL2 port. GPL-3.0.
 *
 * AUTO-GENERATED by c-port/scripts/gen_dispatch.py — do not hand-edit.
 * Re-run the script after Java/XML changes that affect dispatch.
 */
"""


def write_states(states):
    path = GEN_DIR / "dispatch_states.h"
    lines = [HEADER_BANNER, "#ifndef LH_GEN_DISPATCH_STATES_H",
             "#define LH_GEN_DISPATCH_STATES_H", ""]
    lines.append(f"#define LH_GEN_STATE_COUNT {len(states)}")
    lines.append("")
    lines.append("/* Generated state class names — order = lh_state_gen_id enum value. */")
    lines.append("typedef enum {")
    for i, s in enumerate(states):
        lines.append(f"    LH_GEN_{slug(s)} = {i},")
    lines.append(f"    LH_GEN_STATE_MAX = {len(states)}")
    lines.append("} lh_state_gen_id;")
    lines.append("")
    lines.append("static const char* const lh_gen_state_name[LH_GEN_STATE_COUNT] = {")
    for s in states:
        lines.append(f"    \"{s}\",")
    lines.append("};")
    lines.append("")
    lines.append("/* Animation name = simple-name minus 'State' prefix, lowercased. */")
    lines.append("static const char* const lh_gen_state_anim_name[LH_GEN_STATE_COUNT] = {")
    for s in states:
        anim = s[5:].lower() if s.startswith("State") else s.lower()
        lines.append(f"    \"{anim}\",")
    lines.append("};")
    lines.append("")
    lines.append("#endif")
    path.write_text("\n".join(lines), encoding="utf-8")
    return path, len(states)


def write_features(features):
    path = GEN_DIR / "dispatch_features.h"
    lines = [HEADER_BANNER, "#ifndef LH_GEN_DISPATCH_FEATURES_H",
             "#define LH_GEN_DISPATCH_FEATURES_H", ""]
    lines.append(f"#define LH_GEN_FEATURE_COUNT {len(features)}")
    lines.append("")
    lines.append("/* Feature class FQNs harvested from <lionengine:feature> XML nodes. */")
    lines.append("static const char* const lh_gen_feature_class[LH_GEN_FEATURE_COUNT] = {")
    for f in features:
        lines.append(f"    \"{f}\",")
    lines.append("};")
    lines.append("")
    lines.append("#endif")
    path.write_text("\n".join(lines), encoding="utf-8")
    return path, len(features)


def write_entities(classes, setups):
    path = GEN_DIR / "dispatch_entities.h"
    lines = [HEADER_BANNER, "#ifndef LH_GEN_DISPATCH_ENTITIES_H",
             "#define LH_GEN_DISPATCH_ENTITIES_H", ""]
    lines.append(f"#define LH_GEN_ENTITY_CLASS_COUNT {len(classes)}")
    lines.append(f"#define LH_GEN_ENTITY_SETUP_COUNT {len(setups)}")
    lines.append("")
    lines.append("/* <lionengine:class> values appearing in entity XMLs. */")
    lines.append("static const char* const lh_gen_entity_class[LH_GEN_ENTITY_CLASS_COUNT] = {")
    for c in classes: lines.append(f"    \"{c}\",")
    lines.append("};")
    lines.append("")
    lines.append("/* <lionengine:setup> values. */")
    lines.append("static const char* const lh_gen_entity_setup[LH_GEN_ENTITY_SETUP_COUNT] = {")
    for s in setups: lines.append(f"    \"{s}\",")
    lines.append("};")
    lines.append("")
    lines.append("#endif")
    path.write_text("\n".join(lines), encoding="utf-8")
    return path, len(classes) + len(setups)


def write_sequences(seqs):
    path = GEN_DIR / "dispatch_sequences.h"
    lines = [HEADER_BANNER, "#ifndef LH_GEN_DISPATCH_SEQUENCES_H",
             "#define LH_GEN_DISPATCH_SEQUENCES_H", ""]
    lines.append(f"#define LH_GEN_SEQUENCE_COUNT {len(seqs)}")
    lines.append("")
    lines.append("typedef enum {")
    for i, s in enumerate(seqs):
        lines.append(f"    LH_GEN_SEQ_{slug(s)} = {i},")
    lines.append(f"    LH_GEN_SEQUENCE_MAX = {len(seqs)}")
    lines.append("} lh_sequence_gen_id;")
    lines.append("")
    lines.append("static const char* const lh_gen_sequence_name[LH_GEN_SEQUENCE_COUNT] = {")
    for s in seqs:
        lines.append(f"    \"{s}\",")
    lines.append("};")
    lines.append("")
    lines.append("#endif")
    path.write_text("\n".join(lines), encoding="utf-8")
    return path, len(seqs)


def main():
    global GEN_DIR
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(GEN_DIR))
    args = ap.parse_args()
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    GEN_DIR = out

    states  = find_state_classes()
    feats   = find_xml_class_values("feature")
    classes = find_xml_class_values("class")
    setups  = find_xml_class_values("setup")
    seqs    = find_sequence_classes()

    paths = []
    paths.append(write_states(states))
    paths.append(write_features(feats))
    paths.append(write_entities(classes, setups))
    paths.append(write_sequences(seqs))

    for p, n in paths:
        print(f"  wrote {p.relative_to(ROOT)}  ({n} entries)")
    print(f"states={len(states)} features={len(feats)} entity_classes={len(classes)} "
          f"setups={len(setups)} sequences={len(seqs)}")


if __name__ == "__main__":
    main()
